apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ appName }}
  name: {{ appName }}
spec:
  ports:
    - port: 3000
      nodePort: 31323
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ appName }}
  type: NodePort
